//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GESTION_DE_STOCK.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class catgr
    {
        public catgr()
        {
            this.les_articles = new HashSet<les_articles>();
        }
    
        public int id_catgr { get; set; }
        public string nom_catgr { get; set; }
    
        public virtual ICollection<les_articles> les_articles { get; set; }
    }
}
