//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GESTION_DE_STOCK.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class devis
    {
        public devis()
        {
            this.stocks_in = new HashSet<stocks_in>();
        }
    
        public int id_devis { get; set; }
        public int n_facture { get; set; }
        public System.DateTime date_facture { get; set; }
        public int fornisseur_id_fornisseur { get; set; }
    
        public virtual fornisseur fornisseur { get; set; }
        public virtual ICollection<stocks_in> stocks_in { get; set; }
    }
}
