//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GESTION_DE_STOCK.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class forni_activite
    {
        public int id_forni_actv { get; set; }
        public int code_active { get; set; }
        public string nom_active { get; set; }
        public int fornisseur_id_fornisseur { get; set; }
    
        public virtual fornisseur fornisseur { get; set; }
    }
}
