//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GESTION_DE_STOCK.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class fornisseur
    {
        public fornisseur()
        {
            this.devis = new HashSet<devis>();
            this.forni_activite = new HashSet<forni_activite>();
        }
    
        public int id_fornisseur { get; set; }
        public string nom_fornisseur { get; set; }
        public string prenom_fornisseur { get; set; }
        public string societe_fornisseur { get; set; }
        public Nullable<System.DateTime> date_naic_forn { get; set; }
        public string lieu_naic_forn { get; set; }
        public string addrs_forn_pers { get; set; }
        public string addrs_forn_fonct { get; set; }
        public Nullable<int> phone_numbre_forn { get; set; }
        public int num_id_fiscale { get; set; }
        public int num_id_statistique { get; set; }
        public string num_eng_commercial { get; set; }
        public System.DateTime date_eng_commercial { get; set; }
        public int num_bankaire { get; set; }
        public string nom_bankaire { get; set; }
        public string nom_agence_bankaire { get; set; }
    
        public virtual ICollection<devis> devis { get; set; }
        public virtual ICollection<forni_activite> forni_activite { get; set; }
    }
}
