//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GESTION_DE_STOCK.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class les_bon
    {
        public les_bon()
        {
            this.stock_out = new HashSet<stock_out>();
        }
    
        public int id_bon { get; set; }
        public int n_bon { get; set; }
        public System.DateTime date_bon { get; set; }
        public int les_services_id_service { get; set; }
    
        public virtual les_services les_services { get; set; }
        public virtual ICollection<stock_out> stock_out { get; set; }
    }
}
