//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GESTION_DE_STOCK.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class les_services
    {
        public les_services()
        {
            this.les_bon = new HashSet<les_bon>();
        }
    
        public int id_service { get; set; }
        public string nom_service { get; set; }
        public string nom_responsable_srvc { get; set; }
    
        public virtual ICollection<les_bon> les_bon { get; set; }
    }
}
