//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GESTION_DE_STOCK.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class les_articles
    {
        public les_articles()
        {
            this.stocks_in = new HashSet<stocks_in>();
            this.stock_out = new HashSet<stock_out>();
        }
    
        public int id_article { get; set; }
        public string nom_article { get; set; }
        public Nullable<int> quantite_total { get; set; }
        public int catgr_id_catgr { get; set; }
        public Nullable<decimal> prixx_artcl_stock { get; set; }
    
        public virtual ICollection<stocks_in> stocks_in { get; set; }
        public virtual ICollection<stock_out> stock_out { get; set; }
        public virtual catgr catgr { get; set; }
    }
}
