//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GESTION_DE_STOCK.model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gestion_de_stockEntities : DbContext
    {
        public gestion_de_stockEntities()
            : base("name=gestion_de_stockEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<users> usersSet { get; set; }
        public virtual DbSet<les_articles> les_articlesSet { get; set; }
        public virtual DbSet<stocks_in> stocks_inSet { get; set; }
        public virtual DbSet<stock_out> stock_outSet { get; set; }
        public virtual DbSet<fornisseur> fornisseurSet { get; set; }
        public virtual DbSet<devis> devisSet { get; set; }
        public virtual DbSet<les_services> les_servicesSet { get; set; }
        public virtual DbSet<les_bon> les_bonSet { get; set; }
        public virtual DbSet<catgr> catgrSet { get; set; }
        public virtual DbSet<settings> settingsSet { get; set; }
        public virtual DbSet<type_activite_fornisseur> type_activite_fornisseurSet { get; set; }
        public virtual DbSet<forni_activite> forni_activiteSet { get; set; }
    }
}
