//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GESTION_DE_STOCK.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class settings
    {
        public int id_setting { get; set; }
        public int etat_price { get; set; }
        public bool etat_config { get; set; }
    }
}
