//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GESTION_DE_STOCK.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class stocks_in
    {
        public int id_stock_in { get; set; }
        public System.DateTime date_in { get; set; }
        public int quantite_in { get; set; }
        public int les_articles_id_article { get; set; }
        public decimal prix_article { get; set; }
        public int devis_id_devis { get; set; }
        public Nullable<decimal> prix_in_unitaire_x_quntite { get; set; }
    
        public virtual les_articles les_articles { get; set; }
        public virtual devis devis { get; set; }
    }
}
