//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GESTION_DE_STOCK.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class stock_out
    {
        public int id_stock_out { get; set; }
        public System.DateTime date_out { get; set; }
        public int quantite_out { get; set; }
        public int les_articles_id_article { get; set; }
        public int les_bon_id_bon { get; set; }
        public decimal prix_article_out { get; set; }
        public Nullable<decimal> prix_out_unitaire_x_quantite { get; set; }
    
        public virtual les_articles les_articles { get; set; }
        public virtual les_bon les_bon { get; set; }
    }
}
