//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GESTION_DE_STOCK.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class type_activite_fornisseur
    {
        public int id_activi_forn { get; set; }
        public int code_activite { get; set; }
        public string nom_activite { get; set; }
    }
}
